name: CI/CD for Nest.js App

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Generate Sitemap
        run: npm run postbuild

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my2ls .

      - name: Push Docker image to registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag my2ls:latest harutyunianarthur/my2ls:latest
          docker push harutyunianarthur/my2ls:latest

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Deploy to Server
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@${{ secrets.CONTABO_MY2LS_IP }} -p 22 "
            set -e  # Exit if any command fails
          
            # Ensure Docker is running
            systemctl restart docker || true
          
            # Stop and remove existing container if it exists
            if [ \$(docker ps -a -q -f name=my2ls-container) ]; then
              docker stop my2ls-container || true
              docker rm my2ls-container || true
            fi
          
            # Pull the latest Docker image
            docker pull harutyunianarthur/my2ls
          
            # Run the new container
            docker run -d --restart unless-stopped -e PORT='3000' -e NODE_ENV='production' --name my2ls-container -p 3000:3000 harutyunianarthur/my2ls
          "